### ISSUE TITLE
13주차 스터디 후기

### ISSUE THREAD

**Issue by zoolake** [MLifeFam/cs_interview#123]
## 내용
13주차 스터디 후기 적어주세요~

**Comment by zoolake** [comment]
## 선점 스케줄링
- 기아현상 설명 추가
- 오타교정

**Comment by Kyun2da** [comment]
## 단편화

- 오타 수정

**Comment by Jongminfire** [comment]
## 페이지 교체 알고리즘
- FIFO 알고리즘과 LRU 알고리즘에 사용되는 자료구조
- 이외에 다른 페이징 교체 알고리즘이 있는지?

## 주제 조사
- 컴퓨터구조 추가 주제 조사하기

**Comment by HelloNaks** [comment]
##이분 탐색

어디서 사용되는지 찾기
오타 수정
