### ISSUE TITLE
주차마다 주제정하는 큰틀에 관해서 제안합니다.

### ISSUE THREAD

**Issue by kouym7979** [MLifeFam/cs_interview#22]
## 내용
제목과 같이 한 주차에 대한 발표가 끝나면 다음 주차는 그 전에 했던 주제와 다른 주제로 하면 혹시 모를 면접을 대비해 조금이라도 다양한 영역을 공부할 수 있지 않을까 싶습니다..!

ex) 5월3일 자료구조 ->5월 10일 자료구조를 제외한 다른 주제 

이런 방식입니다.

**Comment by Kyun2da** [comment]
나쁘지 않은 것 같네요

**Comment by Jongminfire** [comment]
좋은 의견인 것 같습니다~

**Comment by Kyun2da** [comment]
의견 반영 완료되서 이슈 닫습니다!
