### ISSUE TITLE
문서 내 이미지 파일 관리에 대해 제안합니다

### ISSUE THREAD

**Issue by Jongminfire** [MLifeFam/cs_interview#25]
## 문제 내용

 현재 방식대로 `docs/[주제]/img/` 에 이미지를 위치시키면 로컬에서는 이미지 로드가 가능하나 빌드 할 때 이미지를 불러오지 못합니다.

## 제안 내용

마크다운 작성법 페이지와 호스팅 사이트를 참고 했을 때 이미지 파일을  `static` 폴더 내에 위치시켜야 하는 것 같습니다.

따라서 문서 내 이미지 파일 관리를 `static/img/[대주제]/[소주제]` 형식으로 관리하는 것 제안합니다.

기존에 있는 `docs/자료구조/img/Binary-Search-Inorder.png` 파일을 예시로 들어보면  `static/img/Data-Structure/Binary-Search-Tree/Binary-Search-Inorder.png` 로 위치시킨 뒤, 작성하는 문서에서 

~~~md
![Binary-Search-Inorder](/img/Data-Structure/Binary-Search-Tree/Binary-Search-Inorder.png)
~~~

로 불러오는 방식입니다.

(로컬에서 테스트 해본 결과 `[대주제]`와 `[소주제]` 폴더명이 한글이면 폴더 내 파일을 불러오지 못해서 폴더명은 영어로 해야 하는 것 같습니다)

**Comment by Kyun2da** [comment]
네 알겠습니다~ 앞으로 이렇게 하는걸로 통일해요

**Comment by kouym7979** [comment]
네 참고하겠습니다~

**Comment by zoolake** [comment]
네 알겠습니다!

**Comment by Kyun2da** [comment]
모두 인지하여 이슈 닫습니다.
