### ISSUE TITLE
마크다운 파일 내에 수학 기호 작성을 위한 latex 문법 사용 방법

### ISSUE THREAD

**Issue by Kyun2da** [MLifeFam/cs_interview#27]
## 내용

[latex 문법 변환 사이트](http://www.hostmath.com/)

위 사이트에 가서 원하는 기호로 변환해서 문서에 복사 붙여 넣기를 합니다.

복사 붙여 넣기 할때 $수학기호$ 이런식으로 양 옆에 $를 추가해주면 됩니다.

ex) 루트 ab : \sqrt{ab}

문서에 붙여넣을 때:

$\sqrt{ab}$

혹시 문제 있거나 질문 있으면 아래에 코멘트 바랍니다.

**Comment by Jongminfire** [comment]
유용하게 쓸 수 있을 것 같습니다~

**Comment by Kyun2da** [comment]
모두들 인지 해서 이슈 닫습니다~
