### ISSUE TITLE
마크다운 글상자 (:::) 스타일 제안 합니다.

### ISSUE THREAD

**Issue by Jongminfire** [MLifeFam/cs_interview#38]
## 내용

마크다운 글상자 ( `:::` 문법 ) 의 배경색이 쨍해서 문서를 읽을 때 불편하다는 느낌이 들었습니다.
따라서 마크다운 글상자 배경색의 변경을 제안해보려고 하는데 어떤 의견인지 자유롭게 얘기해봤으면 좋겠습니다.

글상자 배경색의 예시로는 다음과 같습니다

| 변경 전                                                      | 변경 후                                                      |
| :------------------------------------------------------------: | :------------------------------------------------------------: |
| ![danger](https://user-images.githubusercontent.com/51112542/117264902-a9113b80-ae8e-11eb-923a-41c3992283fc.PNG) | ![danger-after](https://user-images.githubusercontent.com/51112542/117265103-d9f17080-ae8e-11eb-945c-e1a3c0bd56bd.PNG) |
| ![tip-before](https://user-images.githubusercontent.com/51112542/117265133-e249ab80-ae8e-11eb-81d6-68e478546b9d.PNG) | ![tip-after](https://user-images.githubusercontent.com/51112542/117265174-ed9cd700-ae8e-11eb-9516-7cef9b9bcd86.PNG) |

<br/>

다양한 의견 부탁드립니다~

**Comment by Kyun2da** [comment]
좋아요~

**Comment by Jongminfire** [comment]
> 좋아요~
> 아니면 투명도 말고 아예색을 바꿔도좋을것 같습니다

아 예시는 투명도 말고 아예 색을 바꿨습니다~

**Comment by HelloNaks** [comment]
저는 초록색 빨간색은 좋은거 같고 투명도만 저정도로 바꾸면 좋을 것 같습니다!

**Comment by HongEunho** [comment]
사진에 나온 투명도는 너무흐려보이는데 투명도를 조금 조절하는것도 괜찮을것같아요~

**Comment by kouym7979** [comment]
좋아요~~ 변경 후는 확실히 좀 많이 흐린 색 같고 약간만 더 밝으면 딱 좋을 것 같아요~

**Comment by zoolake** [comment]
전보다 보기 편해서 좋습니다!
