### ISSUE TITLE
깃 커밋 컨벤션 제안합니다.

### ISSUE THREAD

**Issue by Kyun2da** [MLifeFam/cs_interview#6]
## 내용

feat : 새로운 개념 문서 추가
fix : 버그 수정 (ex. 배포에러)
docs : 기타 README 같은 홈페이지에 영향을 주지 않는 문서 수정이나 등록
style : 내용에 변화는 없지만 스타일 수정 필요할 때 (ex. 마침표 수정, 띄어쓰기 수정, 단락 줄바꿈 등등)
test : 배포 테스트 또는 기타 다른 테스트

#### Title(Subject) 부분 (필수 o)

feat : 머지소트 개념문서 추가
fix : netlify 배포에러 수정
docs : README파일 ~~내용 수정
style : 머지소트 개념문서 단락 줄바꿈 변경
test : 자동 배포 테스트

#### Body 부분 (필수 x)
작성자가 추가적으로 작성하고 싶은 것 자유 작성

#### footer 부분 (필수 x)
자유 작성

이렇게 커밋하는거 어떻게들 생각하시나요?

자유로운 의견 아래에 공유 부탁드립니다~

**Comment by Jongminfire** [comment]
좋습니다 그럼 추가한 개념 문서 수정 시에는 feat인가요?

**Comment by Kyun2da** [comment]
> 좋습니다 그럼 추가한 개념 문서 수정 시에는 feat인가요?

그게 좋은 것 같은데 Update로 하나 추가해도 좋을 것 같네요.

**Comment by HongEunho** [comment]
무슨 말씀이신지 이해가 잘 안가서요 ㅠㅠ 금욜 회의때 좀 배워가야겠습니다~~

**Comment by kouym7979** [comment]
네~  좋은 것같아요

**Comment by zoolake** [comment]
좋습니다!!
