### ISSUE TITLE
앞으로의 스터디 주제 제안합니다.

### ISSUE THREAD

**Issue by Kyun2da** [MLifeFam/cs_interview#7]
# 주제 제안

스터디 주제 제안합니다.

## 개발 상식

- [ ] 좋은 코드란 무엇인가?
- [ ] 객체 지향 프로그래밍이란 무엇인가?
- [ ] RESTFul API 란?
- [ ] TDD 란 무엇이며 어떠한 장점이 있는가?
- [ ] 애자일은 무엇인가?
- [ ] 데브옵스란
- [ ] 서드 파티란
- [ ] 마이크로 서비스 아키텍쳐란
- [ ] 함수형 프로그래밍이란?
- [ ] MVC 패턴이란 무엇인가?
- [ ] Git 과 GitHub 에 대해서

## 자료구조

- [ ] 배열 vs 연결리스트
- [ ] 스택 vs 큐
- [ ] 트리
- [ ] 힙
- [ ] 이진 탐색 트리
- [ ] B Tree & B+ Tree
- [ ] 레드 블랙 트리
- [ ] 해시 테이블
- [ ] 트라이
- [ ] 트리 맵
- [ ] 그래프

## 알고리즘

- [ ] 선택 정렬
- [ ] 거품 정렬
- [ ] 병합 정렬
- [ ] 삽입 정렬
- [ ] 퀵 정렬
- [ ] 힙 정렬
- [ ] 기수 정렬
- [ ] 계수 정렬
- [ ] 투포인터 알고리즘
- [ ] 순열
- [ ] BFS & DFS
- [ ] 최장 증가 수열 (LIS)
- [ ] 최소 공통 조상 (LCA)
- [ ] 동적 계획법
- [ ] 비트 마스크
- [ ] 이분 탐색
- [ ] 최대공약수와 최소공배수

## 컴퓨터 구조와 운영체제

- [ ] 컴퓨터의 구성
- [ ] CPU 원리
- [ ] 고정 소수점 & 부동 소수점
- [ ] 패리티 비트 & 해밍 코드
- [ ] 프로세스와 스레드
- [ ] 동기화 문제
- [ ] Context Switching
- [ ] 인터럽트
- [ ] 시스템 콜
- [ ] 교착 상태
- [ ] CPU 스케줄링
- [ ] 스케줄러의 종류
- [ ] 동기 vs 비동기
- [ ] 페이징 & 세그멘테이션
- [ ] 페이지 교체 알고리즘
- [ ] 단편화
- [ ] IPC
- [ ] 가상 메모리
- [ ] 캐시
- [ ] 파일 시스템

## 데이터 베이스

- [ ] 데이터 베이스 기본 용어
- [ ] Key
- [ ] SQL injection
- [ ] SQL - join
- [ ] SQL vs NOSQL
- [ ] 이상
- [ ] 인덱스
- [ ] 트랜잭션
- [ ] 트랜잭션 격리 수준

## 네트워크

- [ ] OSI 7계층
- [ ] TCP
- [ ] UDP
- [ ] 3 - way handshake & 4-way handshake
- [ ] HTTP와 HTTPS 차이
- [ ] 공개키 암호, 대칭키 암호
- [ ] REST & RESTful
- [ ] 쿠키와 세션의 차이
- [ ] Naver를 치면 일어나는 과정
- [ ] 로드 밸런싱
- [ ] Blocking & Non-Blocking I/O
- [ ] HTTP method
- [ ] DNS round robin 방식

## 디자인 패턴

- [ ] 디자인 패턴 개요
- [ ] 어댑터 패턴
- [ ] 싱글톤 패턴
- [ ] 템플릿 메소드 패턴
- [ ] 팩토리 메소드 패턴
- [ ] 옵저버 패턴
- [ ] 스트레티지 패턴

**Comment by Kyun2da** [comment]
앞으로 스터디 할 것들 주제 뽑아 봤어요.
참고 url은 다음과 같습니다.
[Ready-For-Tech-Interview](https://github.com/WooVictory/Ready-For-Tech-Interview)
[Interview_Question_for_Beginner](https://github.com/JaeYeopHan/Interview_Question_for_Beginner)
[tech-interview-for-developer](https://github.com/gyoogle/tech-interview-for-developer)

앞으로 더 추가할 주제가 있거나 하나의 주제로 통합하고자 하면 여기 아래에 코멘트 달아주세요.

**Comment by kouym7979** [comment]
오... 아주 좋습니다
